name: Release update 🎺

on:
  push:
      branches:    
        - main
      tags:
        - .*
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd ./Examples/tootsdk-release && swift build -v
    - name: Send post
      run: ./.build/debug/tootsdk-release make-post -u ${{ secrets.TOOT_URL }} -u ${{ secrets.TOOT_TOKEN }}
